stop();
_root.glossary.McKeyTermAngle1._visible = false;
_root.glossary.McKeyTermAngle2._visible = false;
_root.doCreateSlide();
_root.title._visible = true;
_root.top._y = _root.top_initial._y;
_root.sideNavcontent._visible = true;
_root.sideNav._visible = true;
_root.sideexample._visible = true;
_root.sideNav.dis.gotoAndStop(1);
_root.map.enabled = true;
_root.glossary._visible = false;
_root.m_c.gotoAndStop("hide");
_root.calculator._visible = false;
_root.l_s.gotoAndStop("map");
_global.quizSection = false;
_root.doPutBackAndFinished();
_root.loadSWFMovie();
_global.timing1 = false;
_global.timing2 = false;
_global.timing3 = false;
_global.timing4 = false;
_global.timing5 = false;
_global.timing6 = false;
_global.timing7 = false;
