// HFR sample viewer: a stand-in for the My Lesson host that plays compiled pages.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { HfrPlayer } from "../runtime/player";

const SAMPLES = [
  { title: "NMS Lesson 7 · Ratios & Proportions (Grade 6, 52 pages)", dir: "../out/nms002-l07/" },
  { title: "ALG Lesson 8 · P040 game + P050 final quiz", dir: "../out/alg001-l08-p040-p050/" },
];
const $ = (id: string) => document.getElementById(id)!;
const canvas = $("stage") as HTMLCanvasElement;
let lesson: any = null, verification: any = null, dir = "", index = 0, started = false, playing = false, spanish: HTMLAudioElement | null = null, lang: "en" | "es" = "en";
const logEl = $("log");
(window as any).hfrViewer = { get player() { return player; } }; // debugging hook for engineers
const player = new HfrPlayer(canvas, {
  onHost: (c) => {
    const row = document.createElement("div");
    row.innerHTML = `<span class="tick">#${c.tick}</span><span class="kind">${esc(c.kind)}</span> ${esc(c.args.map((a) => JSON.stringify(a)).join(", "))}`;
    logEl.prepend(row); while (logEl.childElementCount > 300) logEl.lastElementChild!.remove();
  },
});
const esc = (s: string) => String(s).replace(/[&<>]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[ch]!);

function highlight(src: string): string {
  return esc(src).replace(/(\/\*[\s\S]*?\*\/|\/\/[^\n]*)|("(?:\\.|[^"\\])*")|\b(const|let|return|if|else|for|of|while|do|break|continue|export|default|function|import|type|from|new|undefined|null|true|false)\b|\b(\d+(?:\.\d+)?)\b/g,
    (m, com, str, kw, num) => (com ? `<span class="c">${com}</span>` : str ? `<span class="s">${str}</span>` : kw ? `<span class="k">${kw}</span>` : `<span class="n">${num}</span>`));
}
function resize() { const r = canvas.getBoundingClientRect(); const dpr = Math.min(2, window.devicePixelRatio || 1); const w = Math.round(r.width * dpr), h = Math.round(r.height * dpr); if (w && h && (canvas.width !== w || canvas.height !== h)) { canvas.width = w; canvas.height = h; if (player.rt) player.renderer.render(player.rt); } }
new ResizeObserver(resize).observe(canvas);

async function openSample(i: number) {
  dir = SAMPLES[i].dir;
  lesson = await (await fetch(dir + "lesson.json")).json();
  try { verification = await (await fetch(dir + "verification.json")).json(); } catch { verification = null; }
  const nav = $("outline"); nav.innerHTML = "";
  let section = "";
  lesson.pages.forEach((p: any, k: number) => {
    if (p.sectionCode !== section) { section = p.sectionCode; const h = document.createElement("h2"); h.textContent = `${p.sectionName ?? section} · ${section}`; nav.append(h); }
    const v = verification?.pages.find((x: any) => x.id === p.animationId);
    const b = document.createElement("button"); b.dataset.k = String(k);
    b.innerHTML = `<span class="ord">${p.ordinal}</span><span class="t">${esc(p.titleEnglish ?? p.file)}</span>${v?.same ? '<span class="ok" title="Generated TypeScript behaves identically to the original bytecode">✓</span>' : ""}`;
    b.onclick = () => openPage(k); nav.append(b);
  });
  await openPage(0);
}
async function openPage(k: number) {
  index = Math.max(0, Math.min(lesson.pages.length - 1, k)); const p = lesson.pages[index];
  document.querySelectorAll("nav button").forEach((b) => b.setAttribute("aria-current", String((b as HTMLElement).dataset.k === String(index))));
  $("pageTitle").textContent = `${p.titleEnglish ?? p.file}`;
  $("pageSub").textContent = `${p.lessonTitle} · ${p.sectionName ?? p.sectionCode} · ${p.file}.swf → ${p.animationId}`;
  logEl.innerHTML = ""; stopSpanish();
  const pageDir = `${dir}${p.dir}/`;
  const [ts] = await Promise.all([fetch(`${pageDir}${p.animationId}.ts`).then((r) => r.text()), player.load(`${pageDir}${p.animationId}.data.json`)]);
  $("tsCode").innerHTML = highlight(ts);
  const v = verification?.pages.find((x: any) => x.id === p.animationId); const d = player.data;
  ($("esBtn") as HTMLButtonElement).disabled = !d.spanishAudio; $("esNote").textContent = d.spanishAudio ? "" : "No Spanish narration file for this page";
  $("info").innerHTML = `<table>
    <tr><td>Placement</td><td>${esc(p.animationId)}</td></tr>
    <tr><td>Source SWF</td><td>${esc(d.source.path)}<br><span class="note">SWF ${d.source.swfVersion} · sha256 ${d.source.sha256.slice(0, 16)}…</span></td></tr>
    <tr><td>Generated by</td><td>${esc(d.compiler)}</td></tr>
    <tr><td>Scripts (TypeScript functions)</td><td>${d.stats.scripts}</td></tr>
    <tr><td>Code bodies structured</td><td>${d.stats.codeBodies - d.stats.fallbackBodies} of ${d.stats.codeBodies}</td></tr>
    <tr><td>Characters (shapes, text, sprites…)</td><td>${d.stats.characters}</td></tr>
    <tr><td>Media files</td><td>${d.stats.mediaFiles}${d.spanishAudio ? " + Spanish narration" : ""}</td></tr>
    <tr><td>Differential check</td><td>${v ? (v.same ? `<span class="badge">Identical behaviour</span><br><span class="note">${v.clicks} controls exercised, ${v.hostCalls} shell calls, ${v.ticks} frames, compared with the original bytecode</span>` : `Differs: ${esc(v.diff)}`) : "not run"}</td></tr>
  </table>`;
  ($("prevBtn") as HTMLButtonElement).disabled = index === 0; ($("nextBtn") as HTMLButtonElement).disabled = index === lesson.pages.length - 1;
  resize();
  if (started) { player.start(); playing = true; if (lang === "es") startSpanish(); } else { playing = false; }
  updatePlay();
}
function updatePlay() { $("playBtn").textContent = playing ? "❚❚ Pause" : "▶ Play"; }
function stopSpanish() { if (spanish) { spanish.pause(); spanish = null; } player.audio?.setMuted(false); }
function startSpanish() { const d = player.data; if (!d?.spanishAudio) return; spanish = new Audio(player.baseUrl + d.spanishAudio); player.audio.setMuted(true); spanish.play().catch(() => undefined); }
$("startBtn").onclick = () => { started = true; $("startOverlay").style.display = "none"; player.start(); playing = true; updatePlay(); canvas.focus(); };
$("playBtn").onclick = () => { if (!started) return ($("startBtn") as HTMLButtonElement).click(); if (playing) { player.pause(); spanish?.pause(); } else { player.start(); spanish?.play(); } playing = !playing; updatePlay(); };
$("replayBtn").onclick = () => openPage(index);
$("prevBtn").onclick = () => openPage(index - 1);
$("nextBtn").onclick = () => openPage(index + 1);
$("enBtn").onclick = () => { lang = "en"; $("enBtn").setAttribute("aria-pressed", "true"); $("esBtn").setAttribute("aria-pressed", "false"); stopSpanish(); };
$("esBtn").onclick = () => { lang = "es"; $("esBtn").setAttribute("aria-pressed", "true"); $("enBtn").setAttribute("aria-pressed", "false"); stopSpanish(); if (started) startSpanish(); };
document.querySelectorAll(".tabs button").forEach((b) => (b as HTMLElement).addEventListener("click", () => {
  document.querySelectorAll(".tabs button").forEach((x) => x.setAttribute("aria-selected", String(x === b)));
  document.querySelectorAll(".tab").forEach((t) => t.classList.toggle("on", t.id === `tab-${(b as HTMLElement).dataset.tab}`));
}));
const sel = $("lessonSel") as HTMLSelectElement;
SAMPLES.forEach((s, i) => { const o = document.createElement("option"); o.value = String(i); o.textContent = s.title; sel.append(o); });
sel.onchange = () => openSample(Number(sel.value));
const q = new URLSearchParams(location.search);
sel.value = String(Number(q.get("sample") ?? 0));
openSample(Number(q.get("sample") ?? 0)).then(() => { if (q.get("page")) openPage(Number(q.get("page"))); });
