import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {Container} from '@/components/ui';
import {Link} from '@/i18n/navigation';
import {catalogSummary, getCatalog} from '@/lib/catalog';
import {
  isMigrationStatusAvailable,
  isMigrationStatusDesignerViewRequested,
} from '@/lib/migration-status-access';

export const metadata: Metadata = {title: 'Migration status', robots: {index: false, follow: false}};
export const dynamic = 'force-dynamic';
type Query = Record<string, string | string[] | undefined>;
const SIZE = 75, MISSING_SIZE = 100;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? '' : value ?? '';
function href(query: Query, field: 'page' | 'missingPage', page: number) {const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) {if (key === field) continue; const normalized = first(value); if (normalized) params.set(key, normalized);} if (page > 1) params.set(field, String(page)); return `/migration-status${params.size ? `?${params}` : ''}`;}

export default async function MigrationStatusPage({params, searchParams}: {params: Promise<{locale: 'en' | 'es'}>; searchParams: Promise<Query>}) {
  const [{locale}, query] = await Promise.all([params, searchParams]);
  if (!isMigrationStatusAvailable() || !isMigrationStatusDesignerViewRequested(query.view)) notFound();
  const es = locale === 'es', catalog = getCatalog(), summary = catalogSummary(catalog);
  const status = first(query.status), collection = first(query.collection), grade = first(query.grade), lesson = first(query.lesson), keyword = first(query.q).trim().toLowerCase();
  const filtered = catalog.animations.filter((item) => (!status || item.migration.status === status) && (!collection || item.classification.collection === collection) && (!grade || String(item.classification.grade ?? '') === grade) && (!lesson || String(item.classification.lesson ?? '') === lesson) && (!keyword || `${item.animationId} ${item.assetId} ${item.source.path} ${item.classification.titleDisplay}`.toLowerCase().includes(keyword)));
  const pages = Math.max(1, Math.ceil(filtered.length / SIZE)), page = Math.min(pages, Math.max(1, Number.parseInt(first(query.page) || '1', 10) || 1)), visible = filtered.slice((page - 1) * SIZE, page * SIZE);
  const missingPages = Math.max(1, Math.ceil(catalog.missingReferences.length / MISSING_SIZE)), missingPage = Math.min(missingPages, Math.max(1, Number.parseInt(first(query.missingPage) || '1', 10) || 1)), missing = catalog.missingReferences.slice((missingPage - 1) * MISSING_SIZE, missingPage * MISSING_SIZE);
  return <main id="main-content"><header className="archive-page-header archive-page-header--status"><Container><p className="eyebrow">{es ? 'Registro interno' : 'Internal ledger'}</p><h1>{es ? 'Estado de migración' : 'Migration status'}</h1><p>{es ? 'El progreso procede del registro estricto, no de afirmaciones manuales.' : 'Progress comes from the strict ledger, never a hand-edited completion claim.'}</p><dl className="status-metrics"><div><dt>{es ? 'Rutas' : 'Paths'}</dt><dd>{summary.paths.toLocaleString(locale)}</dd></div><div><dt>{es ? 'Canónicos' : 'Canonical'}</dt><dd>{summary.canonical}</dd></div><div><dt>{es ? 'Alias' : 'Aliases'}</dt><dd>{summary.aliases}</dd></div><div><dt>{es ? 'Completos' : 'Complete'}</dt><dd>{summary.complete}</dd></div><div><dt>{es ? 'Bloqueados' : 'Blocked'}</dt><dd>{summary.blocked}</dd></div><div><dt>{es ? 'Faltantes' : 'Missing'}</dt><dd>{summary.missing}</dd></div></dl></Container></header>
    <section className="ledger-section"><Container><form className="ledger-filters" method="get"><input name="view" type="hidden" value="designer" /><label><span>{es ? 'Buscar' : 'Search'}</span><input defaultValue={first(query.q)} name="q" /></label><label><span>{es ? 'Estado' : 'Status'}</span><select defaultValue={status} name="status"><option value="">{es ? 'Todos' : 'All'}</option>{Object.keys(summary.statusCounts).sort().map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{es ? 'Tipo' : 'Type'}</span><select defaultValue={collection} name="collection"><option value="">{es ? 'Todos' : 'All'}</option><option>course</option><option>keyterm</option><option>formula</option></select></label><label><span>{es ? 'Grado' : 'Grade'}</span><input defaultValue={grade} name="grade" /></label><label><span>{es ? 'Lección' : 'Lesson'}</span><input defaultValue={lesson} name="lesson" /></label><button type="submit">{es ? 'Filtrar' : 'Filter'}</button></form>
      <div className="ledger-summary"><p><strong>{filtered.length}</strong> {es ? 'rutas coincidentes' : 'matching paths'}</p><span>{es ? `Página ${page} de ${pages}` : `Page ${page} of ${pages}`}</span></div><div className="ledger-table-wrap"><table className="ledger-table"><thead><tr><th>{es ? 'Animación' : 'Animation'}</th><th>{es ? 'Clasificación' : 'Classification'}</th><th>{es ? 'Fuente' : 'Source'}</th><th>{es ? 'Estado' : 'Status'}</th></tr></thead><tbody>{visible.map((item) => <tr key={item.animationId}><td><Link href={`/animations/${item.animationId}`}>{item.animationId}</Link>{!item.isCanonical ? <small>{es ? 'alias de' : 'alias of'} {item.canonicalAnimationId}</small> : null}</td><td><strong>{item.classification.collection}</strong><small>{item.classification.grade ?? '—'} · L{item.classification.lesson ?? '—'} · {item.classification.section?.code ?? '—'}</small></td><td><code>{item.source.path}</code><small>{item.source.swf.frameCount ?? '—'} frames · {item.audio.length} audio</small></td><td><span className={`status-chip status-chip--${item.migration.status}`}>{item.migration.status}</span></td></tr>)}</tbody></table></div><nav className="pagination">{page > 1 ? <Link href={href(query, 'page', page - 1)}>← {es ? 'Anterior' : 'Previous'}</Link> : <span />}{page < pages ? <Link href={href(query, 'page', page + 1)}>{es ? 'Siguiente' : 'Next'} →</Link> : <span />}</nav>
      <details className="missing-references" open={Boolean(first(query.missingPage))}><summary>{catalog.missingReferences.length} {es ? 'referencias faltantes' : 'missing-source references'}</summary><ul>{missing.map((item) => <li key={item.id}><code>{item.path}</code><span>{item.titleEnglish}{item.titleSpanish ? ` / ${item.titleSpanish}` : ''} · {item.collection} · {item.grade ?? '—'} · {item.occurrenceCount} refs</span></li>)}</ul><nav className="pagination">{missingPage > 1 ? <Link href={href(query, 'missingPage', missingPage - 1)}>← {es ? 'Anterior' : 'Previous'}</Link> : <span />}<span>{missingPage} / {missingPages}</span>{missingPage < missingPages ? <Link href={href(query, 'missingPage', missingPage + 1)}>{es ? 'Siguiente' : 'Next'} →</Link> : <span />}</nav></details>
    </Container></section></main>;
}
