import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {fileURLToPath} from 'node:url';

import {
  analyzeRendererSource,
  auditCanvasResolution,
  canonicalJson,
  computeProfileChecksumSet,
  parseArguments,
  reportBytes,
  writeOrCheckReport,
} from './audit-canvas-resolution.mjs';

const ONE_PIXEL_PNG =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2ZfQAAAAASUVORK5CYII=';
const TEST_TEMP_PARENT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../work',
);

function digest(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function fixtureRenderer({
  animationId,
  bitmap = false,
  vectorFont = true,
  fillText = false,
  actualFilter = false,
} = {}) {
  return `/* Generated by scripts/build-safe-ffdec-canvas-adapter.mjs. */
(function () {
"use strict";
var Filters = {};
Filters._cut = function (value) {
  return value;
};
Filters.blur = function (value) {
  return Filters._cut(value);
};
Filters.glow = function (value) {
  return Filters.blur(value);
};
${vectorFont ? 'function font12(ctx,ch,textColor){ return ch + textColor; }' : ''}
var image = {src: ""};
${bitmap ? `image.src = "data:image/PNG;base64,${ONE_PIXEL_PNG}";` : ''}
if (typeof image.src !== "string" || image.src.indexOf("data:image/") !== 0) {
  throw new Error("invalid image");
}
function render(targetCanvas, request) {
  if (!targetCanvas || typeof targetCanvas.getContext !== "function") {
    throw new Error("targetCanvas must provide a context");
  }
  if (targetCanvas.width !== 800 || targetCanvas.height !== 600) {
    throw new Error("targetCanvas must be exactly 800x600");
  }
  var ctx = targetCanvas.getContext("2d");
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ${fillText ? 'ctx.fillText("fixture", 1, 2);' : ''}
  ${actualFilter ? 'Filters.glow(ctx);' : ''}
  return {animationId: "${animationId}", request: request};
}
return render;
})();
`;
}

function fixtureContract(checksumSetSha256, profileSha256 = null) {
  return {
    contractId: 'fixture-production-contract-v1',
    profile: {
      profileId: 'fixture-current-js-production-assets-v1',
      sha256: profileSha256,
      checksumSetSha256,
      counts: {public: 3, serverAudio: 0, total: 3},
    },
    nativeCanvas: {
      width: 800,
      height: 600,
      rootTransform: [1, 0, 0, 1, 0, 0],
    },
    placements: [
      {
        lessonId: 'fixture-l01',
        releaseId: 'fixture-release-1',
        ordinal: 1,
        placementId: 'fixture-l01-placement-001',
        animationId: 'fixture-renderer-a',
        xmlOccurrence: 1,
        sourcePath: 'fixture/L1/A.swf',
        sourceSha256: 'a'.repeat(64),
      },
      {
        lessonId: 'fixture-l01',
        releaseId: 'fixture-release-1',
        ordinal: 2,
        placementId: 'fixture-l01-placement-002',
        animationId: 'fixture-renderer-a',
        xmlOccurrence: 2,
        sourcePath: 'fixture/L1/A.swf',
        sourceSha256: 'a'.repeat(64),
      },
      {
        lessonId: 'fixture-l01',
        releaseId: 'fixture-release-1',
        ordinal: 3,
        placementId: 'fixture-l01-placement-003',
        animationId: 'fixture-renderer-b',
        xmlOccurrence: 3,
        sourcePath: 'fixture/L1/B.swf',
        sourceSha256: 'b'.repeat(64),
      },
      {
        lessonId: 'fixture-l02',
        releaseId: 'fixture-release-2',
        ordinal: 1,
        placementId: 'fixture-l02-placement-001',
        animationId: 'fixture-renderer-c',
        xmlOccurrence: 1,
        sourcePath: 'fixture/L2/C.swf',
        sourceSha256: 'c'.repeat(64),
      },
    ],
    lessons: [
      {
        lessonId: 'fixture-l01',
        grade: 1,
        lesson: 1,
        releaseId: 'fixture-release-1',
        placementCount: 3,
        uniqueRendererCount: 2,
        repeatedPlacements: [
          {animationId: 'fixture-renderer-a', occurrenceCount: 2},
        ],
      },
      {
        lessonId: 'fixture-l02',
        grade: 1,
        lesson: 2,
        releaseId: 'fixture-release-2',
        placementCount: 1,
        uniqueRendererCount: 1,
        repeatedPlacements: [],
      },
    ],
    pilotRendererIds: ['fixture-renderer-a', 'fixture-renderer-c'],
    expectedRendererFamilies: {'safe-ffdec-canvas-adapter': 3},
    oneOffSpecialRendererIds: [],
  };
}

async function createFixture(t) {
  await mkdir(TEST_TEMP_PARENT, {recursive: true});
  const root = await mkdtemp(
    path.join(TEST_TEMP_PARENT, '.canvas-resolution-audit-test-'),
  );
  t.after(async () => rm(root, {recursive: true, force: true}));
  const definitions = [
    {
      animationId: 'fixture-renderer-a',
      releaseId: 'fixture-release-1',
      source: fixtureRenderer({
        animationId: 'fixture-renderer-a',
        bitmap: true,
        vectorFont: true,
        fillText: true,
        actualFilter: true,
      }),
    },
    {
      animationId: 'fixture-renderer-b',
      releaseId: 'fixture-release-1',
      source: fixtureRenderer({
        animationId: 'fixture-renderer-b',
        vectorFont: true,
      }),
    },
    {
      animationId: 'fixture-renderer-c',
      releaseId: 'fixture-release-2',
      source: fixtureRenderer({
        animationId: 'fixture-renderer-c',
        bitmap: true,
        vectorFont: false,
      }),
    },
  ];
  const entries = [];
  for (const definition of definitions) {
    const relativePath = `${definition.animationId}/canvas-renderer.js`;
    const assetPath = `courses/${relativePath}`;
    const absolutePath = path.join(
      root,
      'apps/web/public/flash-assets/courses',
      definition.animationId,
      'canvas-renderer.js',
    );
    await mkdir(path.dirname(absolutePath), {recursive: true});
    const bytes = Buffer.from(definition.source);
    await writeFile(absolutePath, bytes);
    entries.push({
      assetPath,
      relativePath,
      storageRoot: 'public',
      releaseId: definition.releaseId,
      bytes: bytes.length,
      sha256: digest(bytes),
    });
  }
  entries.sort((left, right) => left.assetPath.localeCompare(right.assetPath));
  const checksumSetSha256 = computeProfileChecksumSet(entries);
  const profile = {
    schemaVersion: 1,
    profileId: 'fixture-current-js-production-assets-v1',
    generatedBy: 'fixture',
    approvalScope: 'fixture-production-five',
    approvedReleaseIds: ['fixture-release-1', 'fixture-release-2'],
    counts: {public: 3, serverAudio: 0, total: 3},
    checksumSetSha256,
    entries,
  };
  const profilePath = path.join(root, 'fixture-profile.json');
  const profileBytes = Buffer.from(`${JSON.stringify(profile, null, 2)}\n`);
  await writeFile(profilePath, profileBytes);
  return {
    root,
    profilePath,
    contract: fixtureContract(checksumSetSha256, digest(profileBytes)),
    definitions,
  };
}

test('small renderer fixture separates bitmap/filter facts from safety helpers', () => {
  const source = fixtureRenderer({
    animationId: 'fixture-renderer-a',
    bitmap: true,
    fillText: true,
    actualFilter: true,
  });
  const analysis = analyzeRendererSource({
    animationId: 'fixture-renderer-a',
    releaseId: 'fixture-release-1',
    source,
    contract: fixtureContract(null),
  });
  assert.deepEqual(analysis.nativeCanvas, {
    guard: {width: 800, height: 600, occurrenceCount: 1},
    rootTransform: [1, 0, 0, 1, 0, 0],
    contractMatched: true,
  });
  assert.equal(analysis.embeddedBitmaps.occurrenceCount, 1);
  assert.equal(analysis.embeddedBitmaps.uniqueDecodedImageCount, 1);
  assert.equal(analysis.embeddedBitmaps.excludedSafetyLiteralCount, 1);
  assert.deepEqual(analysis.embeddedBitmaps.images[0].mime, ['image/png']);
  assert.deepEqual(
    analysis.embeddedBitmaps.images[0].detectedMime,
    ['image/png'],
  );
  assert.equal(analysis.embeddedBitmaps.images[0].intrinsicWidth, 1);
  assert.equal(analysis.embeddedBitmaps.images[0].intrinsicHeight, 1);
  assert.equal(
    analysis.embeddedBitmaps.images[0].disposition,
    'preserve-source-bitmap-and-mark-resolution-ceiling',
  );
  assert.equal(
    analysis.embeddedBitmaps.images[0].maxAuthoredDrawArea.status,
    'not-statically-proven',
  );
  assert.equal(analysis.vectorFonts.functionOccurrenceCount, 1);
  assert.deepEqual(analysis.vectorFonts.functionNames, ['font12']);
  assert.equal(analysis.fillText.occurrenceCount, 1);
  assert.equal(analysis.filters.helperDefinitionCount, 3);
  assert.equal(analysis.filters.helperInternalCallCount, 2);
  assert.equal(analysis.filters.actualPlacementCount, 1);
  assert.deepEqual(analysis.filters.actualPlacements, [
    {method: 'glow', occurrenceCount: 1},
  ]);
});

test('fixture profile produces deterministic placement, family, and bitmap audit', async (t) => {
  const fixture = await createFixture(t);
  const first = await auditCanvasResolution({
    projectRoot: fixture.root,
    profilePath: fixture.profilePath,
    scope: 'production-five',
    contract: fixture.contract,
  });
  const second = await auditCanvasResolution({
    projectRoot: fixture.root,
    profilePath: fixture.profilePath,
    scope: 'production-five',
    contract: fixture.contract,
  });
  assert.deepEqual(first, second);
  assert.equal(first.payload.denominator.placementCount, 4);
  assert.equal(first.payload.denominator.uniqueRendererCount, 3);
  assert.equal(first.payload.denominator.courseShellCount, 0);
  assert.equal(first.payload.summary.rendererCount, 3);
  assert.equal(first.payload.summary.bitmapRendererCount, 2);
  assert.equal(first.payload.summary.bitmapOccurrenceCount, 2);
  assert.equal(first.payload.summary.uniqueDecodedBitmapCount, 1);
  assert.equal(first.payload.summary.vectorFontRendererCount, 2);
  assert.equal(first.payload.summary.fillTextRendererCount, 1);
  assert.equal(first.payload.summary.actualFilterRendererCount, 1);
  assert.equal(first.payload.summary.actualFilterPlacementCount, 1);
  assert.deepEqual(
    first.payload.rendererFamilies.map(({family, rendererCount}) => ({
      family,
      rendererCount,
    })),
    [{family: 'safe-ffdec-canvas-adapter', rendererCount: 3}],
  );
  assert.equal(
    first.payload.embeddedBitmaps.excludedSafetyLiteralCount,
    3,
  );
  assert.equal(
    first.payload.embeddedBitmaps.uniqueDecodedImages[0].rendererCount,
    2,
  );
  assert.deepEqual(
    first.payload.embeddedBitmaps.uniqueDecodedImages[0].sourceBindings.map(
      ({animationId}) => animationId,
    ),
    ['fixture-renderer-a', 'fixture-renderer-c'],
  );
  assert.equal(
    first.payload.embeddedBitmaps.uniqueDecodedImages[0].intrinsicWidth,
    1,
  );
  assert.equal(
    first.payload.bitmapResolutionCeilingInventory.bitmapBoundRendererCount,
    2,
  );
  assert.equal(
    first.payload.bitmapResolutionCeilingInventory.bitmapBoundPlacementCount,
    3,
  );
  assert.equal(
    first.payload.bitmapResolutionCeilingInventory.bitmapPlacementRowCount,
    3,
  );
  assert.equal(
    first.payload.bitmapResolutionCeilingInventory.ownerApprovalGate,
    'blocked-pending-owner-review',
  );
  assert.deepEqual(
    first.payload.bitmapResolutionCeilingInventory.rows.map(
      ({placementId, animationId, sourcePath}) => ({
        placementId,
        animationId,
        sourcePath,
      }),
    ),
    [
      {
        placementId: 'fixture-l01-placement-001',
        animationId: 'fixture-renderer-a',
        sourcePath: 'fixture/L1/A.swf',
      },
      {
        placementId: 'fixture-l01-placement-002',
        animationId: 'fixture-renderer-a',
        sourcePath: 'fixture/L1/A.swf',
      },
      {
        placementId: 'fixture-l02-placement-001',
        animationId: 'fixture-renderer-c',
        sourcePath: 'fixture/L2/C.swf',
      },
    ],
  );
  assert.equal(first.payload.pilotCoverage.presentRendererCount, 2);
  assert.equal(
    first.payload.inputs.rendererFileVerification.selectedRendererCount,
    3,
  );
  assert.equal(
    first.payloadSha256,
    digest(Buffer.from(canonicalJson(first.payload))),
  );
  assert.ok(reportBytes(first).equals(reportBytes(second)));
});

test('pilot scope keeps the full denominator and hashes only pilot renderers', async (t) => {
  const fixture = await createFixture(t);
  const document = await auditCanvasResolution({
    projectRoot: fixture.root,
    profilePath: fixture.profilePath,
    scope: 'pilot',
    contract: fixture.contract,
  });
  assert.equal(document.payload.denominator.placementCount, 4);
  assert.equal(document.payload.denominator.uniqueRendererCount, 3);
  assert.deepEqual(document.payload.selection.rendererIds, [
    'fixture-renderer-a',
    'fixture-renderer-c',
  ]);
  assert.equal(document.payload.summary.rendererCount, 2);
  assert.equal(
    document.payload.inputs.rendererFileVerification.profileRendererCount,
    3,
  );
  assert.equal(
    document.payload.inputs.rendererFileVerification.selectedRendererCount,
    2,
  );
  assert.equal(document.payload.pilotCoverage.analyzedInSelectedScopeCount, 2);
});

test('missing profile fails closed with the explicit --profile remedy', async (t) => {
  const fixture = await createFixture(t);
  await assert.rejects(
    auditCanvasResolution({
      projectRoot: fixture.root,
      profilePath: path.join(fixture.root, 'missing-profile.json'),
      scope: 'pilot',
      contract: fixture.contract,
    }),
    /Pass --profile <path>/u,
  );
});

test('production-bound audit rejects profile byte drift even when JSON data is unchanged', async (t) => {
  const fixture = await createFixture(t);
  const original = await readFile(fixture.profilePath);
  await writeFile(fixture.profilePath, Buffer.concat([
    original.subarray(0, original.length - 1),
    Buffer.from('  \n'),
  ]));
  await assert.rejects(
    auditCanvasResolution({
      projectRoot: fixture.root,
      profilePath: fixture.profilePath,
      scope: 'production-five',
      contract: fixture.contract,
    }),
    /profile file SHA-256 is outside the audit contract/u,
  );
});

test('write/check mode byte-compares a recomputed report and rejects drift', async (t) => {
  const fixture = await createFixture(t);
  const document = await auditCanvasResolution({
    projectRoot: fixture.root,
    profilePath: fixture.profilePath,
    scope: 'pilot',
    contract: fixture.contract,
  });
  const outputPath = path.join(fixture.root, 'output', 'audit.json');
  const written = await writeOrCheckReport({
    document,
    outputPath,
    projectRoot: fixture.root,
  });
  assert.equal(written.operation, 'write');
  const identical = await writeOrCheckReport({
    document,
    outputPath,
    projectRoot: fixture.root,
  });
  assert.equal(identical.operation, 'existing-identical');
  const checked = await writeOrCheckReport({
    document,
    outputPath,
    check: true,
    projectRoot: fixture.root,
  });
  assert.equal(checked.operation, 'check');
  const current = await readFile(outputPath);
  await writeFile(outputPath, Buffer.concat([current, Buffer.from(' ')]));
  await assert.rejects(
    writeOrCheckReport({
      document,
      outputPath,
      projectRoot: fixture.root,
    }),
    /refusing to overwrite immutable audit evidence/u,
  );
  await assert.rejects(
    writeOrCheckReport({
      document,
      outputPath,
      check: true,
      projectRoot: fixture.root,
    }),
    /output is stale/u,
  );
});

test('argument parser supports the audit CLI and closes invalid check usage', () => {
  assert.deepEqual(
    parseArguments([
      '--scope=pilot',
      '--profile',
      'profile.json',
      '--output=report.json',
      '--check',
    ]),
    {
      profilePath: 'profile.json',
      scope: 'pilot',
      outputPath: 'report.json',
      check: true,
      help: false,
    },
  );
  assert.throws(
    () => parseArguments(['--scope', 'all']),
    /expected pilot or production-five/u,
  );
  assert.throws(
    () => parseArguments(['--check']),
    /requires --output/u,
  );
  assert.throws(
    () => parseArguments(['--unknown']),
    /unknown argument/u,
  );
});
