import assert from "node:assert/strict";
import {mkdtemp, readFile, rm} from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

import {
  generateAdaptiveCanvasFile,
  planAdaptiveCanvas,
  sha256,
} from "./generate-adaptive-canvas.mjs";

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TEST_TEMP_PARENT = path.join(PROJECT_ROOT, "work");
const FIXTURE_ID = "course-g04-l03-fixture-001";
const FIXTURE_WIDTH = 4;
const FIXTURE_HEIGHT = 3;
const SAFE_RENDERER = path.join(
  PROJECT_ROOT,
  "apps/web/public/flash-assets/courses/course-g04-l03-ts-006/canvas-renderer.js",
);
const SAFE_RENDERER_SHA256 =
  "162d67f65d72f307d27339d7a5f4d7945936b47854cc0fa8b6055455ac843252";
const IN009_RENDERER = path.join(
  PROJECT_ROOT,
  "apps/web/public/flash-assets/courses/course-g04-l03-in-009/canvas-renderer.js",
);
const IN009_RENDERER_SHA256 =
  "74bc5717fe3ddebcb4a4371717cd4c93e24e211414d8f58108dc368f64afdb34";

function fixtureSource() {
  return `/* Generated by scripts/build-safe-ffdec-canvas-adapter.mjs. */
/* Engineering candidate only: no strict, human, or owner acceptance is implied. */
(function (global) {
"use strict";
var scalingGrids = {};
var embeddedBitmapEvidence = "data:image/png;base64,AA==";
var METADATA = deepFreeze({
  "schemaVersion": 1,
  "animationId": "${FIXTURE_ID}",
  "stage": {
    "width": ${FIXTURE_WIDTH},
    "height": ${FIXTURE_HEIGHT},
    "backgroundColor": "#102030"
  }
});
var readyPromise = null;

function deepFreeze(value) {
    if (value && typeof value === "object" && !Object.isFrozen(value)) {
        Object.freeze(value);
        Object.keys(value).forEach(function (key) { deepFreeze(value[key]); });
    }
    return value;
}

function ready() {
    if (readyPromise === null) readyPromise = Promise.resolve();
    return readyPromise;
}

function resolveFrameState(request) {
    request = request || {};
    return Object.freeze({frame: request.frame === undefined ? 1 : request.frame});
}

function render(targetCanvas, request) {
    if (!targetCanvas || typeof targetCanvas.getContext !== "function") {
        throw new Error("targetCanvas must provide a 2D canvas context");
    }
    if (targetCanvas.width !== ${FIXTURE_WIDTH} || targetCanvas.height !== ${FIXTURE_HEIGHT}) {
        throw new Error("targetCanvas must be exactly ${FIXTURE_WIDTH}x${FIXTURE_HEIGHT}");
    }
    var state = resolveFrameState(request);
    var ctx = targetCanvas.getContext("2d");
    if (!ctx) throw new Error("2D canvas context is unavailable");
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.fillStyle = "#102030";
    ctx.fillRect(0, 0, targetCanvas.width, targetCanvas.height);
    ctx.fillStyle = "#e04020";
    ctx.fillRect(1, 1, 2, 1);
    return state;
}

var registry = global["HELP_MATH_CANVAS_ASSETS"];
if (registry === undefined) {
    registry = Object.create(null);
    Object.defineProperty(global, "HELP_MATH_CANVAS_ASSETS", {value: registry});
}
registry["${FIXTURE_ID}"] = Object.freeze({metadata: METADATA, ready: ready, resolveFrameState: resolveFrameState, render: render});
})(globalThis);
`;
}

function fixturePlan(source = fixtureSource()) {
  const inputBytes = Buffer.from(source, "utf8");
  return planAdaptiveCanvas({
    inputBytes,
    expectedInputSha256: sha256(inputBytes),
    animationId: FIXTURE_ID,
    stageWidth: FIXTURE_WIDTH,
    stageHeight: FIXTURE_HEIGHT,
    inputPath: "fixture/canvas-renderer.js",
    outputPath: "fixture/canvas-renderer.adaptive.js",
  });
}

function parseHexColor(value) {
  assert.match(value, /^#[a-f0-9]{6}$/i);
  return [
    Number.parseInt(value.slice(1, 3), 16),
    Number.parseInt(value.slice(3, 5), 16),
    Number.parseInt(value.slice(5, 7), 16),
    255,
  ];
}

function makeRasterCanvas(width, height) {
  const pixels = Buffer.alloc(width * height * 4);
  let transform = [1, 0, 0, 1, 0, 0];
  let fillStyle = "#000000";
  const context = {
    setTransform(a, b, c, d, e, f) {
      transform = [a, b, c, d, e, f];
    },
    get fillStyle() {
      return fillStyle;
    },
    set fillStyle(value) {
      fillStyle = value;
    },
    fillRect(x, y, rectWidth, rectHeight) {
      const [a, b, c, d, e, f] = transform;
      assert.equal(b, 0);
      assert.equal(c, 0);
      const left = Math.round(x * a + e);
      const top = Math.round(y * d + f);
      const right = Math.round((x + rectWidth) * a + e);
      const bottom = Math.round((y + rectHeight) * d + f);
      const rgba = parseHexColor(fillStyle);
      for (let py = Math.max(0, top); py < Math.min(height, bottom); py += 1) {
        for (let px = Math.max(0, left); px < Math.min(width, right); px += 1) {
          const offset = (py * width + px) * 4;
          pixels.set(rgba, offset);
        }
      }
    },
  };
  return {
    width,
    height,
    pixels,
    context,
    getContext(kind) {
      return kind === "2d" ? context : null;
    },
  };
}

function loadFixtureRuntime(source) {
  const sandbox = {};
  vm.createContext(sandbox);
  new vm.Script(source, {filename: "canvas-renderer.fixture.js"}).runInContext(sandbox);
  return sandbox.HELP_MATH_CANVAS_ASSETS[FIXTURE_ID];
}

function pixelAt(canvas, x, y) {
  const offset = (y * canvas.width + x) * 4;
  return [...canvas.pixels.subarray(offset, offset + 4)];
}

test("adaptive-v1 k=1 preserves fixture RGBA bytes in a VM", () => {
  const originalSource = fixtureSource();
  const generated = fixturePlan(originalSource);
  const originalRuntime = loadFixtureRuntime(originalSource);
  const adaptiveRuntime = loadFixtureRuntime(generated.outputBytes.toString("utf8"));
  const originalCanvas = makeRasterCanvas(FIXTURE_WIDTH, FIXTURE_HEIGHT);
  const adaptiveCanvas = makeRasterCanvas(FIXTURE_WIDTH, FIXTURE_HEIGHT);

  assert.equal(originalRuntime.render(originalCanvas, {frame: 1}).frame, 1);
  assert.equal(
    adaptiveRuntime.render(adaptiveCanvas, {frame: 1, renderScale: 1}).frame,
    1,
  );
  assert.deepEqual(adaptiveCanvas.pixels, originalCanvas.pixels);
  assert.equal(generated.receipt.lane, "adaptive-v1");
  assert.equal(generated.receipt.structure.inputTransformCounts.authoredRootIdentityTransforms, 1);
  assert.equal(generated.receipt.structure.outputTransformCounts.authoredRootAdaptiveTransforms, 1);
  assert.equal(generated.receipt.structure.inputTransformCounts.embeddedBitmapDataUriCount, 1);
  assert.equal(generated.receipt.structure.outputTransformCounts.embeddedBitmapDataUriCount, 1);
});

test("adaptive-v1 k=2 requires exact backing and scales authored RGBA pixels", () => {
  const generated = fixturePlan();
  const runtime = loadFixtureRuntime(generated.outputBytes.toString("utf8"));
  const nativeRuntime = loadFixtureRuntime(fixtureSource());
  const nativeCanvas = makeRasterCanvas(FIXTURE_WIDTH, FIXTURE_HEIGHT);
  nativeRuntime.render(nativeCanvas, {frame: 1});

  assert.throws(
    () => runtime.render(makeRasterCanvas(FIXTURE_WIDTH * 2, FIXTURE_HEIGHT * 2 - 1), {
      frame: 1,
      renderScale: 2,
    }),
    /targetCanvas must be exactly 8x6 for renderScale 2/,
  );

  const doubledCanvas = makeRasterCanvas(FIXTURE_WIDTH * 2, FIXTURE_HEIGHT * 2);
  runtime.render(doubledCanvas, {frame: 1, renderScale: 2});
  for (let y = 0; y < FIXTURE_HEIGHT; y += 1) {
    for (let x = 0; x < FIXTURE_WIDTH; x += 1) {
      const expected = pixelAt(nativeCanvas, x, y);
      for (let dy = 0; dy < 2; dy += 1) {
        for (let dx = 0; dx < 2; dx += 1) {
          assert.deepEqual(pixelAt(doubledCanvas, x * 2 + dx, y * 2 + dy), expected);
        }
      }
    }
  }
});

test("adaptive-v1 rejects missing renderScale and k=3 before drawing", () => {
  const generated = fixturePlan();
  const runtime = loadFixtureRuntime(generated.outputBytes.toString("utf8"));
  assert.throws(
    () => runtime.render(makeRasterCanvas(FIXTURE_WIDTH, FIXTURE_HEIGHT), {frame: 1}),
    /renderScale must be exactly 1 or 2/,
  );
  const canvas = makeRasterCanvas(FIXTURE_WIDTH * 3, FIXTURE_HEIGHT * 3);
  assert.throws(
    () => runtime.render(canvas, {frame: 1, renderScale: 3}),
    /renderScale must be exactly 1 or 2/,
  );
  assert.equal(canvas.pixels.every((value) => value === 0), true);
});

test("hash, animation, and native-stage provenance are fail-closed", () => {
  const source = Buffer.from(fixtureSource(), "utf8");
  assert.throws(
    () => planAdaptiveCanvas({
      inputBytes: source,
      expectedInputSha256: "0".repeat(64),
      animationId: FIXTURE_ID,
      stageWidth: FIXTURE_WIDTH,
      stageHeight: FIXTURE_HEIGHT,
    }),
    (error) => error.code === "INPUT_SHA256_MISMATCH",
  );
  assert.throws(
    () => planAdaptiveCanvas({
      inputBytes: source,
      expectedInputSha256: sha256(source),
      animationId: "course-g04-l10-wrong-001",
      stageWidth: FIXTURE_WIDTH,
      stageHeight: FIXTURE_HEIGHT,
    }),
    (error) => error.code === "ANIMATION_ID_MISMATCH",
  );
  assert.throws(
    () => planAdaptiveCanvas({
      inputBytes: source,
      expectedInputSha256: sha256(source),
      animationId: FIXTURE_ID,
      stageWidth: FIXTURE_WIDTH + 1,
      stageHeight: FIXTURE_HEIGHT,
    }),
    (error) => error.code === "NATIVE_STAGE_MISMATCH",
  );
});

test("unknown extra authored transforms fail closed to the special lane", () => {
  const ambiguous = fixtureSource().replace(
    "    ctx.setTransform(1, 0, 0, 1, 0, 0);",
    "    ctx.setTransform(1, 0, 0, 1, 0, 0);\n    ctx.setTransform(1, 0, 0, 1, 0, 0);",
  );
  const bytes = Buffer.from(ambiguous, "utf8");
  assert.throws(
    () => planAdaptiveCanvas({
      inputBytes: bytes,
      expectedInputSha256: sha256(bytes),
      animationId: FIXTURE_ID,
      stageWidth: FIXTURE_WIDTH,
      stageHeight: FIXTURE_HEIGHT,
    }),
    (error) => error.code === "UNSUPPORTED_RENDERER_STRUCTURE" && error.lane === "special",
  );
});

test("the actual IN-009 multi-reset and mask renderer is routed to special", async () => {
  const inputBytes = await readFile(IN009_RENDERER);
  assert.equal(sha256(inputBytes), IN009_RENDERER_SHA256);
  assert.throws(
    () => planAdaptiveCanvas({
      inputBytes,
      expectedInputSha256: IN009_RENDERER_SHA256,
      animationId: "course-g04-l03-in-009",
      stageWidth: 800,
      stageHeight: 600,
    }),
    (error) =>
      error.code === "SPECIAL_LANE_REQUIRED" &&
      error.lane === "special" &&
      /multi-reset/.test(error.message),
  );
});

test("a hash-pinned existing renderer generates one runtime and a SHA receipt", async () => {
  const temporary = await mkdtemp(path.join(TEST_TEMP_PARENT, ".adaptive-canvas-v1-test-"));
  const outputPath = path.join(temporary, "course-g04-l03-ts-006.adaptive.js");
  const receiptPath = path.join(temporary, "course-g04-l03-ts-006.receipt.json");
  try {
    const receipt = await generateAdaptiveCanvasFile({
      inputPath: SAFE_RENDERER,
      outputPath,
      receiptPath,
      expectedInputSha256: SAFE_RENDERER_SHA256,
      animationId: "course-g04-l03-ts-006",
      stageWidth: 800,
      stageHeight: 600,
    });
    const [sourceAfter, outputBytes, receiptBytes] = await Promise.all([
      readFile(SAFE_RENDERER),
      readFile(outputPath),
      readFile(receiptPath),
    ]);
    const persistedReceipt = JSON.parse(receiptBytes.toString("utf8"));
    assert.equal(sha256(sourceAfter), SAFE_RENDERER_SHA256);
    assert.equal(receipt.input.sha256, SAFE_RENDERER_SHA256);
    assert.equal(receipt.output.sha256, sha256(outputBytes));
    assert.equal(persistedReceipt.output.sha256, receipt.output.sha256);
    assert.deepEqual(receipt.resolution, {
      schemaVersion: 1,
      mode: "adaptive-integer",
      nativeWidth: 800,
      nativeHeight: 600,
      supportedRenderScales: [1, 2],
    });
    assert.equal(receipt.structure.supportedProfile, "safe-ffdec-static-no-source-reset-v1");
    assert.deepEqual(receipt.structure.inputTransformCounts, {
      standaloneContextSetTransformCalls: 3,
      offscreenContextSetTransformCalls: 0,
      directResetTransformCalls: 0,
      clipCalls: 9,
      globalCompositeOperationReferences: 12,
      sourceStrokeResetSites: 0,
      scalingGridAssignments: 0,
      rootFrameImageTableReferences: 0,
      authoredRootIdentityTransforms: 1,
      authoredRootAdaptiveTransforms: 0,
      renderContextSetTransformCalls: 1,
      embeddedBitmapDataUriCount: 1,
    });
    assert.equal(receipt.boundaries.productionIntegration, false);
    assert.equal(receipt.boundaries.ownerAcceptance, false);
    assert.equal(receipt.boundaries.releaseOrPublication, false);
  } finally {
    await rm(temporary, {recursive: true, force: true});
  }
});

test("prototype file generation refuses production renderer output paths", async () => {
  const blockedOutput = path.join(
    PROJECT_ROOT,
    "apps/web/public/flash-assets/courses/__adaptive-prototype-must-not-write.js",
  );
  await assert.rejects(
    generateAdaptiveCanvasFile({
      inputPath: SAFE_RENDERER,
      outputPath: blockedOutput,
      receiptPath: `${blockedOutput}.json`,
      expectedInputSha256: SAFE_RENDERER_SHA256,
      animationId: "course-g04-l03-ts-006",
      stageWidth: 800,
      stageHeight: 600,
    }),
    (error) => error.code === "PRODUCTION_OUTPUT_BLOCKED",
  );
});
